### PR TITLE
CONTRIBUTING.md: modern feature bit assignment.

### PR DESCRIPTION
**Pull request by rustyrussell**
1. Put it in the PR title so everyone can see.
2. Deploy with +100 while it's still unratified, in case it changes.

### CODE REVIEW

**Review by t-bast — APPROVED** [review]
ACK

**Review by carlaKC — APPROVED** [review]

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/lightning/bolts/pull/1108/commits/58473d03216d50b59c13be682bf2dbeef2e52f85

**Comment by t-bast** [comment]
Should we extend that recommendation to messages and tlv fields introduced by experimental features?

This isn't strictly necessary: an implementation that wants to support both the experimental version and the official version could encode/decode messages and tlvs differently depending on what feature was negotiated (the experimental feature bit or the official one). But it's a bit cumbersome (at least in eclair we'd rather use separate messages for the experimental version of the feature). Maybe at least worth mentioning that this is a concern that implementers should worry about?

**Review by ProofOfKeags — APPROVED** [review]
ACK

**Pull request merged**
