### PR TITLE
Clarify the sighash types for HTLC Success and Timeout transactions

### PR DESCRIPTION
**Pull request by ksedgwic**

### CODE REVIEW

**Comment by t-bast** [comment]
This is already stated here: https://github.com/lightning/bolts/blob/master/05-onchain.md#generation-of-htlc-transactions
Maybe you can instead just add a link to it?

**Comment by ksedgwic** [comment]
> This is already stated here: https://github.com/lightning/bolts/blob/master/05-onchain.md#generation-of-htlc-transactions Maybe you can instead just add a link to it?

Sounds good, how does this look?

**Review by t-bast — APPROVED** [review]
Thanks, ACK https://github.com/lightning/bolts/pull/954/commits/655915c2520cb7f572edfd3f38ba349369a150be

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/lightning/bolts/pull/954/commits/655915c2520cb7f572edfd3f38ba349369a150be

**Review by TheBlueMatt — APPROVED** [review]

**Comment by rustyrussell** [comment]
Ack 655915c2520cb7f572edfd3f38ba349369a150be

**Pull request merged**
